version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    environment:
      - PORT=4001
      - DB_HOST=host_do_banco
      - DB_USER=usuario
      - DB_PASS=senha
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
